name: feature_auth
description: Authentication feature package - handles login, register, password reset
version: 0.1.0
publish_to: "none"
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  core:
    path: ../core
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
